from pathlib import Path

from openpyxl import load_workbook


ROOT = Path(__file__).resolve().parents[1]
XLSX = ROOT / "outputs" / "AppSheet_Drogueria_Produccion.xlsx"
OUT = ROOT / "outputs" / "Fase_2_Manual_AppSheet_DIGEMID.md"


def load_sheet(wb, name):
    ws = wb[name]
    rows = list(ws.iter_rows(values_only=True))
    headers = [str(value or "") for value in rows[0]]
    data = []
    for raw in rows[1:]:
        row = {headers[i]: raw[i] if i < len(raw) and raw[i] is not None else "" for i in range(len(headers))}
        data.append(row)
    return headers, data


def md_table(headers, rows):
    def clean(value):
        text = str(value or "")
        text = text.replace("|", "\\|").replace("\n", "<br>")
        return text

    out = []
    out.append("| " + " | ".join(headers) + " |")
    out.append("| " + " | ".join(["---"] * len(headers)) + " |")
    for row in rows:
        out.append("| " + " | ".join(clean(row.get(header, "")) for header in headers) + " |")
    return "\n".join(out)


def grouped_config(rows):
    groups = {}
    for row in rows:
        groups.setdefault(row["TABLA"], []).append(row)
    return groups


def build():
    wb = load_workbook(XLSX, data_only=True)
    app_headers, app_rows = load_sheet(wb, "APP_CONFIG")
    formula_headers, formula_rows = load_sheet(wb, "APPSHEET_FORMULAS")
    validation_headers, validation_rows = load_sheet(wb, "APPSHEET_VALIDATIONS")
    action_headers, action_rows = load_sheet(wb, "APPSHEET_ACTIONS")
    view_headers, view_rows = load_sheet(wb, "APPSHEET_VIEWS")
    automation_headers, automation_rows = load_sheet(wb, "APPSHEET_AUTOMATIONS")

    column_headers = [
        "COLUMNA",
        "TIPO_APPSHEET",
        "ES_KEY",
        "ES_LABEL",
        "REF_TABLA",
        "ENUM_VALUES",
        "REQUIRED",
        "EDITABLE",
        "INITIAL_VALUE",
        "VALID_IF",
        "APP_FORMULA",
    ]

    lines = [
        "# Fase 2 - Manual AppSheet DIGEMID",
        "",
        "Objetivo: construir la aplicación en AppSheet usando únicamente Google Sheets + AppSheet. No usar Apps Script, React, backend ni fórmulas de Excel.",
        "",
        "Archivo base:",
        "",
        "`outputs/AppSheet_Drogueria_Produccion.xlsx`",
        "",
        "Tablas operativas que sí se agregan a AppSheet:",
        "",
        "`CONFIG`, `PROVEEDORES`, `CLIENTES`, `PRODUCTOS`, `LOTES`, `INGRESOS`, `EGRESOS`, `DOCUMENTOS`.",
        "",
        "Hojas de apoyo que NO se deben agregar como tablas operativas:",
        "",
        "`APP_CONFIG`, `APPSHEET_FORMULAS`, `APPSHEET_VALIDATIONS`, `APPSHEET_ACTIONS`, `APPSHEET_VIEWS`, `APPSHEET_AUTOMATIONS`, `README`.",
        "",
        "## Paso 1 - Subir el archivo a Google Drive",
        "",
        "1. Abre Google Drive.",
        "2. Haz clic en `Nuevo`.",
        "3. Haz clic en `Subir archivo`.",
        "4. Selecciona `AppSheet_Drogueria_Produccion.xlsx`.",
        "5. Espera a que termine la carga.",
        "6. Haz doble clic sobre el archivo.",
        "7. Haz clic en `Abrir con`.",
        "8. Haz clic en `Hojas de cálculo de Google`.",
        "9. Espera a que Google convierta el archivo.",
        "10. Cambia el nombre del Google Sheet a `BD_DROGUERIA_APPSHEET_PRODUCCION`.",
        "",
        "## Paso 2 - Crear la app en AppSheet",
        "",
        "1. Con el Google Sheet abierto, haz clic en `Extensiones`.",
        "2. Haz clic en `AppSheet`.",
        "3. Haz clic en `Crear una app`.",
        "4. Si AppSheet abre una pestaña nueva, espera a que cargue el editor.",
        "5. Si pide iniciar sesión, inicia sesión con la misma cuenta de Google Drive.",
        "6. En el nombre de app escribe `Droguería Trazabilidad DIGEMID`.",
        "7. Selecciona categoría `Inventory` o `Operations` si AppSheet lo solicita.",
        "8. Haz clic en `Create app` o `Customize your app`.",
        "",
        "Ruta alternativa si no aparece el menú de AppSheet:",
        "",
        "1. Entra a `https://www.appsheet.com`.",
        "2. Haz clic en `Create`.",
        "3. Haz clic en `App`.",
        "4. Haz clic en `Start with existing data`.",
        "5. Selecciona Google Drive.",
        "6. Selecciona `BD_DROGUERIA_APPSHEET_PRODUCCION`.",
        "7. Haz clic en `Select`.",
        "",
        "## Paso 3 - Agregar solo las tablas operativas",
        "",
        "1. En el editor de AppSheet, haz clic en `Data` en el menú izquierdo.",
        "2. Haz clic en `Tables`.",
        "3. Revisa las tablas detectadas automáticamente.",
        "4. Si AppSheet agregó hojas de apoyo, elimínalas de la app:",
        "   `APP_CONFIG`, `APPSHEET_FORMULAS`, `APPSHEET_VALIDATIONS`, `APPSHEET_ACTIONS`, `APPSHEET_VIEWS`, `APPSHEET_AUTOMATIONS`, `README`.",
        "5. Para eliminar una hoja de apoyo: haz clic sobre la tabla, luego clic en `Delete table` o `Remove table from app`.",
        "6. Confirma la eliminación si AppSheet lo solicita.",
        "7. Haz clic en `+ New Table`.",
        "8. Agrega estas tablas una por una si no existen:",
        "   `CONFIG`, `PROVEEDORES`, `CLIENTES`, `PRODUCTOS`, `LOTES`, `INGRESOS`, `EGRESOS`, `DOCUMENTOS`.",
        "9. Para cada tabla, deja `Are updates allowed?` en `Adds, updates, and deletes`.",
        "10. Haz clic en `Save`.",
        "",
        "## Paso 4 - Regenerar columnas",
        "",
        "1. Haz clic en `Data`.",
        "2. Haz clic en `Columns`.",
        "3. Selecciona la tabla `CONFIG`.",
        "4. Haz clic en `Regenerate Structure`.",
        "5. Confirma con `Regenerate`.",
        "6. Repite lo mismo para `PROVEEDORES`, `CLIENTES`, `PRODUCTOS`, `LOTES`, `INGRESOS`, `EGRESOS` y `DOCUMENTOS`.",
        "7. Haz clic en `Save`.",
        "",
        "## Paso 5 - Configurar columnas",
        "",
        "Para cada tabla:",
        "",
        "1. Haz clic en `Data`.",
        "2. Haz clic en `Columns`.",
        "3. Selecciona la tabla indicada.",
        "4. Haz clic en el lápiz de cada columna.",
        "5. Copia exactamente los valores de la tabla siguiente.",
        "6. Guarda cada cambio con `Done`.",
        "7. Al terminar la tabla, haz clic en `Save`.",
        "",
    ]

    for table, rows in grouped_config(app_rows).items():
        lines.extend(
            [
                f"### Tabla {table}",
                "",
                md_table(column_headers, rows),
                "",
            ]
        )

    lines.extend(
        [
            "## Paso 6 - Crear columnas virtuales y pegar App Formula",
            "",
            "1. Haz clic en `Data`.",
            "2. Haz clic en `Columns`.",
            "3. Abre la tabla indicada en la columna `TABLA`.",
            "4. Haz clic en `Add virtual column`.",
            "5. En `Name`, escribe el valor de `COLUMNA`.",
            "6. En `Type`, selecciona `TIPO_APPSHEET`.",
            "7. En `App formula`, pega `FORMULA_APPSHEET`.",
            "8. Haz clic en `Done`.",
            "9. Repite hasta crear todas las columnas de esta lista.",
            "10. Haz clic en `Save`.",
            "",
            md_table(formula_headers, formula_rows),
            "",
            "## Paso 7 - Pegar Valid If y validaciones",
            "",
            "1. Haz clic en `Data`.",
            "2. Haz clic en `Columns`.",
            "3. Selecciona la tabla indicada.",
            "4. Haz clic en la columna indicada.",
            "5. Busca la propiedad indicada en `PROPIEDAD`.",
            "6. Pega la expresión de `EXPRESION`.",
            "7. Si existe `PROPIEDAD_2`, pega también `EXPRESION_2` en esa propiedad.",
            "8. Haz clic en `Done`.",
            "9. Haz clic en `Save`.",
            "",
            md_table(validation_headers, validation_rows),
            "",
            "## Paso 8 - Configurar slices para inspección",
            "",
            "1. Haz clic en `Data`.",
            "2. Haz clic en `Slices`.",
            "3. Haz clic en `+ New Slice`.",
            "4. Crea el slice `STOCK_DISPONIBLE`.",
            "5. En `Source table`, selecciona `LOTES`.",
            "6. En `Row filter condition`, pega:",
            "",
            "```appsheet",
            "[STOCK_ACTUAL] > 0",
            "```",
            "",
            "7. En columnas selecciona: `ID_LOTE`, `ID_PRODUCTO`, `LOTE`, `FECHA_VENCIMIENTO`, `STOCK_ACTUAL`, `ALERTA_VENCIMIENTO`, `ES_LOTE_FEFO`.",
            "8. Haz clic en `Save`.",
            "9. Haz clic en `+ New Slice`.",
            "10. Crea el slice `LOTES_ALERTA_DIGEMID`.",
            "11. En `Source table`, selecciona `LOTES`.",
            "12. En `Row filter condition`, pega:",
            "",
            "```appsheet",
            "AND([STOCK_ACTUAL] > 0, IN([ALERTA_VENCIMIENTO], LIST(\"VENCIDO\", \"VENCE 30 DIAS\", \"VENCE 60 DIAS\", \"VENCE 90 DIAS\")))",
            "```",
            "",
            "13. Haz clic en `Save`.",
            "",
            "## Paso 9 - Crear acciones",
            "",
            "1. Haz clic en `Behavior`.",
            "2. Haz clic en `Actions`.",
            "3. Haz clic en `+ New Action`.",
            "4. En `For a record of this table`, selecciona la tabla indicada.",
            "5. En `Action name`, escribe el valor de `ACCION`.",
            "6. En `Do this`, selecciona `TIPO_ACCION`.",
            "7. En `Target`, pega `EXPRESION`.",
            "8. Haz clic en `Save`.",
            "9. Repite para cada acción.",
            "",
            md_table(action_headers, action_rows),
            "",
            "## Paso 10 - Crear Bots",
            "",
            "1. Haz clic en `Automation`.",
            "2. Haz clic en `Bots`.",
            "3. Haz clic en `+ New Bot`.",
            "4. En `Bot name`, escribe `AUTOMATIZACION`.",
            "5. En `Event`, selecciona el valor de `EVENTO`.",
            "6. En `Table`, selecciona `TABLA`.",
            "7. En condición del evento, pega `CONDICION`.",
            "8. En `Process`, crea un paso nuevo.",
            "9. En `Task`, selecciona `TAREA`.",
            "10. Configura destinatario como el email del responsable técnico o administrador.",
            "11. En el asunto usa el nombre de la automatización.",
            "12. En el cuerpo copia el objetivo y agrega campos del registro.",
            "13. Haz clic en `Save`.",
            "14. Repite con cada Bot.",
            "",
            md_table(automation_headers, automation_rows),
            "",
            "## Paso 11 - Crear Views",
            "",
            "1. Haz clic en `UX`.",
            "2. Haz clic en `Views`.",
            "3. Haz clic en `+ New View`.",
            "4. En `View name`, escribe `VISTA`.",
            "5. En `For this data`, selecciona `TABLA_ORIGEN`.",
            "6. En `View type`, selecciona `TIPO_VISTA`.",
            "7. En `Position`, selecciona `Menu` por ahora.",
            "8. En `Sort by`, usa `ORDEN_SUGERIDO` si aplica.",
            "9. Haz clic en `Save`.",
            "10. Repite con cada vista.",
            "",
            md_table(view_headers, view_rows),
            "",
            "## Paso 12 - Crear Dashboard principal DIGEMID",
            "",
            "1. Haz clic en `UX`.",
            "2. Haz clic en `Views`.",
            "3. Haz clic en `+ New View`.",
            "4. En `View name`, escribe `Dashboard`.",
            "5. En `For this data`, selecciona `Dashboard` si existe; si no existe, selecciona cualquier tabla y luego cambia el tipo a dashboard.",
            "6. En `View type`, selecciona `Dashboard`.",
            "7. En `Position`, selecciona `Primary`.",
            "8. En `View Entries`, agrega estas vistas en este orden:",
            "   `Stock`, `Ingresos`, `Egresos`, `Trazabilidad`, `Documentos`.",
            "9. Activa `Interactive mode`.",
            "10. Haz clic en `Save`.",
            "",
            "## Paso 13 - Configurar pantalla principal optimizada para inspección DIGEMID",
            "",
            "La barra principal debe tener únicamente estas opciones:",
            "",
            "1. `Dashboard`",
            "2. `Ingresos`",
            "3. `Egresos`",
            "4. `Stock`",
            "5. `Trazabilidad`",
            "6. `Clientes`",
            "7. `Proveedores`",
            "8. `Configuración`",
            "",
            "Configuración exacta:",
            "",
            "1. Haz clic en `UX`.",
            "2. Haz clic en `Views`.",
            "3. Abre la vista `Dashboard`.",
            "4. En `Position`, selecciona `Primary`.",
            "5. Abre `Ingresos` y selecciona `Primary`.",
            "6. Abre `Egresos` y selecciona `Primary`.",
            "7. Abre `Stock` y selecciona `Primary`.",
            "8. Abre `Trazabilidad` y selecciona `Primary`.",
            "9. Abre `Clientes` y selecciona `Primary`.",
            "10. Abre `Proveedores` y selecciona `Primary`.",
            "11. Crea o abre la vista `Configuración`.",
            "12. En `For this data`, selecciona `CONFIG`.",
            "13. En `View type`, selecciona `Detail`.",
            "14. En `Position`, selecciona `Primary`.",
            "15. Para `Productos` y `Documentos`, selecciona `Menu` para que no saturen la pantalla principal.",
            "16. Para cualquier vista automática no usada, selecciona `Ref` o `Menu`.",
            "17. Haz clic en `Save`.",
            "",
            "## Paso 14 - Configurar UX general",
            "",
            "1. Haz clic en `UX`.",
            "2. Haz clic en `Options`.",
            "3. En `Starting view`, selecciona `Dashboard`.",
            "4. En `Primary navigation`, deja visibles solo las 8 vistas DIGEMID.",
            "5. En `Table view style`, usa `Table` para Stock, Ingresos y Egresos.",
            "6. En `Detail view`, permite mostrar inline views para trazabilidad.",
            "7. Haz clic en `Save`.",
            "",
            "## Paso 15 - Configurar Branding con logo superior",
            "",
            "1. Haz clic en `UX`.",
            "2. Haz clic en `Brand`.",
            "3. En `App logo`, sube el logo de la droguería.",
            "4. En `App name`, escribe `Droguería - Trazabilidad DIGEMID`.",
            "5. En `Header`, activa la visualización del logo si la opción está disponible.",
            "6. En `Theme`, selecciona un tema claro.",
            "7. En `Primary color`, usa un verde sanitario sobrio.",
            "8. En `Background`, selecciona claro o blanco.",
            "9. Haz clic en `Save`.",
            "",
            "## Paso 16 - Configurar vistas inline de trazabilidad",
            "",
            "1. Haz clic en `Data`.",
            "2. Haz clic en `Columns`.",
            "3. Abre `LOTES`.",
            "4. Confirma que existen las columnas virtuales `RELATED_INGRESOS`, `RELATED_EGRESOS`, `RELATED_DOCUMENTOS`.",
            "5. Haz clic en `UX`.",
            "6. Haz clic en `Views`.",
            "7. Abre la vista `Trazabilidad`.",
            "8. Confirma que usa la tabla `LOTES`.",
            "9. Confirma que el tipo es `Detail`.",
            "10. En columnas visibles, muestra: `ID_PRODUCTO`, `LOTE`, `FECHA_FABRICACION`, `FECHA_VENCIMIENTO`, `STOCK_ACTUAL`, `ALERTA_VENCIMIENTO`, `TRAZABILIDAD_RESUMEN`, `RELATED_INGRESOS`, `RELATED_EGRESOS`, `RELATED_DOCUMENTOS`.",
            "11. Haz clic en `Save`.",
            "",
            "## Paso 17 - Prueba mínima antes de inspección",
            "",
            "1. Haz clic en `Productos`.",
            "2. Haz clic en `+`.",
            "3. Registra un producto activo.",
            "4. Haz clic en `Proveedores`.",
            "5. Haz clic en `+`.",
            "6. Registra un proveedor activo.",
            "7. Abre la tabla `LOTES` desde menú o desde Productos.",
            "8. Haz clic en `+`.",
            "9. Registra un lote con fecha de vencimiento próxima.",
            "10. Haz clic en `Ingresos`.",
            "11. Haz clic en `+`.",
            "12. Registra un ingreso del lote con cantidad 100.",
            "13. Haz clic en `Stock`.",
            "14. Verifica que `STOCK_ACTUAL` sea 100.",
            "15. Haz clic en `Clientes`.",
            "16. Registra un cliente.",
            "17. Haz clic en `Egresos`.",
            "18. Registra una salida de cantidad 10.",
            "19. Verifica que AppSheet solo permita el lote FEFO/FIFO.",
            "20. Vuelve a `Stock`.",
            "21. Verifica que `STOCK_ACTUAL` sea 90.",
            "22. Intenta registrar salida de 1000.",
            "23. Confirma que AppSheet bloquea la salida por stock insuficiente.",
            "24. Abre `Trazabilidad`.",
            "25. Abre el lote.",
            "26. Verifica que se vean ingresos, egresos y documentos relacionados.",
            "",
            "## Paso 18 - Checklist final para publicar",
            "",
            "1. Haz clic en `Manage`.",
            "2. Haz clic en `Author` o `Deploy` según tu editor.",
            "3. Revisa errores.",
            "4. Corrige cualquier columna sin tipo correcto.",
            "5. Confirma que todos los IDs son `Key`.",
            "6. Confirma que labels están asignados.",
            "7. Confirma que refs funcionan.",
            "8. Confirma que `EGRESOS[CANTIDAD]` bloquea cantidad mayor al stock.",
            "9. Confirma que `EGRESOS[ID_LOTE]` solo muestra el lote FEFO/FIFO.",
            "10. Confirma que el dashboard es la pantalla inicial.",
            "11. Confirma que el logo aparece arriba.",
            "12. Haz clic en `Save`.",
        ]
    )

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    build()
